repos:
- repo: local
  hooks:
    - id: nx-affected-terraform-lint
      name: nx-affected-terraform-lint
      entry: nx affected:lint
      language: system
      types: []
      pass_filenames: false