repos:
- repo: local
  hooks:
    - id: nx-affected-pre-commit
      name: nx-affected-pre-commit
      entry: nx affected --target=pre-commit
      language: system
      types: []
      pass_filenames: false